# Generated by Django 4.2.7 on 2023-11-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board", models.CharField(default="         ", max_length=9)),
                ("next_move", models.CharField(default="X", max_length=1)),
            ],
        ),
    ]
